"""
Alembic's migration environment.

Run by the ``alembic`` command as a file, not imported as a module, which is why
everything below happens at import time and why ``alembic.ini`` prepends the
repository root to ``sys.path``.

**The models are the source of truth and this file only points at them.**
``target_metadata`` is ``Base.metadata``, and it is populated by importing
``src.db.models`` — the package's ``__init__`` is what puts the three tables on
the metadata. An autogenerate run against a metadata missing a table does not
fail; it cheerfully writes a migration that drops the table. So the import is
load-bearing and is not an unused one.

Four choices worth stating, because each of them changes what autogenerate is
able to see:

- **Synchronous, on psycopg.** Alembic's migration API is synchronous; the async
  variant runs the same API inside ``asyncio.run`` and buys nothing here, since
  a migration is a one-shot process with one connection. ``src.db.engine`` has
  psycopg configured for the product path already, so the driver name is taken
  from there rather than spelled again.

- **A fresh ``NullPool`` engine rather than ``get_sync_engine()``.** The product
  engine carries the call log's operating parameters and two of them are wrong
  here. Its ``statement_timeout`` is 10 seconds — chosen so a stalled write
  cannot stall a judged run — and a migration waiting on a lock, or building an
  index on a table that has grown, is a statement that may legitimately take
  longer than a model call may. Its pool of five is five connections held on a
  shared pooler for a process that needs one. The connect timeout *is* reused:
  it answers a different question, how long a scale-to-zero instance may take to
  wake, and that answer does not change with the caller.

  The consequence is that a migration runs under the server's own
  ``statement_timeout``, the Supabase project default of two minutes. That is
  the intended behaviour and not an oversight.

- **``compare_type=True``**, stated rather than inherited. It has been Alembic's
  default since 1.12, and the verification this whole setup rests on — apply the
  migration, then autogenerate again and require it to come back empty — is only
  as strong as what the comparison looks at. A default that a future version, or
  a pin moving backwards, could flip is not something to leave implicit.

- **``compare_server_default`` left off**, which is Alembic's default and a real
  limitation rather than an omission. ``created_at`` and ``updated_at`` carry
  ``server_default=func.now()``; changing or removing one of those in
  ``base.py`` **will not** be detected by autogenerate, and the empty-diff check
  will pass over it. Turning it on is known to produce spurious diffs from
  Postgres's own rewriting of default expressions — ``now()`` reflects back
  differently from how it was written — and a check that cries wolf is worse
  than one with a documented blind spot. If a server default ever changes, the
  migration is written by hand.
"""
from __future__ import annotations

import logging

from alembic import context
from sqlalchemy import create_engine, pool

from src.db.engine import (
    CONNECT_TIMEOUT_SECONDS,
    SYNC_DRIVER,
    engine_url,
    raw_url,
    safe_target,
)
from src.db.models import Base
from src.logging_setup import setup_logging

logger = logging.getLogger("alembic.env")

target_metadata = Base.metadata


def include_object(obj, name, type_, reflected, compare_to) -> bool:
    """
    Keep autogenerate's attention on the tables this project declares.

    Without this, **any table in the ``public`` schema that is not in
    ``Base.metadata`` becomes an ``op.drop_table`` in the next autogenerated
    migration.** The database is a Supabase project rather than a private
    instance: things arrive in it that this repository did not create and must
    not remove. The failure mode is not a broken migration — it is a migration
    that applies cleanly and deletes somebody else's table.

    The filter is on tables only. An index or a column belonging to an excluded
    table is never reached, because the table it hangs off was never compared;
    the ones belonging to our own tables must all be seen, or the empty-diff
    check stops meaning anything.

    ``alembic_version`` is excluded by this rule too, correctly — Alembic
    creates and maintains it and has never included it in autogenerate.
    """
    if type_ == "table":
        return name in target_metadata.tables
    return True


def run_migrations_offline() -> None:
    """
    Emit SQL to stdout instead of connecting — ``alembic upgrade head --sql``.

    Useful for reading the DDL before it is applied to a database with no undo,
    and it is how the initial migration was reviewed. The URL is still required,
    but only its dialect is used; nothing is sent anywhere.
    """
    context.configure(
        url=_migration_url(),
        target_metadata=target_metadata,
        include_object=include_object,
        compare_type=True,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """
    Connect and run the migrations in **one transaction for the whole upgrade**.

    That is Alembic's default and it is the right one on Postgres, where DDL is
    transactional: a chain of three migrations that fails in the third leaves
    the database as it was, rather than two-thirds migrated with no record of
    which third. ``transaction_per_migration`` would trade that for the ability
    to migrate past a statement Postgres will not run inside a transaction; no
    such statement is in the chain, and adding one should be a deliberate act.
    """
    connectable = create_engine(
        _migration_url(),
        # One connection, used once, released at exit. The pooling that makes
        # sense for a run writing a row per model call is overhead for a process
        # that opens a connection, runs DDL and stops.
        poolclass=pool.NullPool,
        connect_args={"connect_timeout": CONNECT_TIMEOUT_SECONDS},
    )
    logger.info("Migrating %s", safe_target())
    try:
        with connectable.connect() as connection:
            context.configure(
                connection=connection,
                target_metadata=target_metadata,
                include_object=include_object,
                compare_type=True,
            )
            with context.begin_transaction():
                context.run_migrations()
    finally:
        connectable.dispose()


def _migration_url():
    """
    ``DB_URL`` on the psycopg driver, or a refusal naming the missing setting.

    Absent ``DB_URL`` means *do not write* everywhere else in this project — the
    call log's gate, and the reason a fresh clone runs without infrastructure.
    Here it can only mean a mistake: a migration with nothing to migrate has no
    silent-skip reading. ``SystemExit`` rather than an exception so the command
    reports the setting rather than a traceback ending in ``None``.
    """
    raw = raw_url()
    if not raw:
        raise SystemExit(
            "DB_URL is not set — alembic has no database to migrate. "
            "Set it in .env, or in the environment for a one-off target."
        )
    return engine_url(raw, SYNC_DRIVER)


setup_logging()
# SQLAlchemy's engine logger emits every statement it executes when its
# effective level reaches INFO, which `setup_logging` sets on the root logger.
# For a migration that means the DDL twice — once from Alembic's own progress
# lines and once as echoed SQL — so the engine is muted here rather than the
# root level lowered, which would also mute Alembic.
logging.getLogger("sqlalchemy.engine").setLevel(logging.WARNING)

if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()