"""create the llm call log

Revision ID: f5c1763874f3
Revises:
Created: 2026-08-26 15:09:15.727623

The three tables of ``src/db/models/llm_log.py``, as autogenerated against the
live instance while it was still empty. **The body below is Alembic's output
verbatim** — nothing was tidied, reordered or renamed. A hand-edit here is a
divergence between the migration and the models that the empty-diff check can
no longer see, because that check compares the *database* to the models and a
database built by an edited migration would simply be wrong in both places.

Two things in it are worth reading rather than skipping, since both would have
been mistakes had they come out differently:

- **Every constraint is named.** ``pk_llm_attempt``,
  ``fk_llm_call_run_id_llm_run``, ``ix_llm_call_run_id`` — from the naming
  convention on ``Base.metadata``, which is why that convention had to exist
  before this file rather than after. Postgres would otherwise have invented
  the names, and ``downgrade`` would be dropping constraints by strings nobody
  chose.
- **``llm_attempt`` is created first and dropped last**, because ``llm_call``
  holds the only foreign key in the schema and Alembic sorted the tables by
  their dependencies rather than by the order they appear in the models.

Applied and verified 2026-08-26: ``upgrade head`` against the live instance,
followed by an autogenerate that came back empty.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f5c1763874f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_attempt',
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('llm_server', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generation_id', sa.String(), nullable=True),
    sa.Column('served_provider', sa.String(), nullable=True),
    sa.Column('model_alias', sa.String(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=True),
    sa.Column('finish_reason', sa.String(), nullable=True),
    sa.Column('request_seconds', sa.Float(), nullable=False),
    sa.Column('routing_chain', sa.String(), nullable=True),
    sa.Column('native_finish_reason', sa.String(), nullable=True),
    sa.Column('generation_time', sa.Float(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('attempt_id', name=op.f('pk_llm_attempt'))
    )
    op.create_index(op.f('ix_llm_attempt_call_id'), 'llm_attempt', ['call_id'], unique=False)
    op.create_index(op.f('ix_llm_attempt_generation_id'), 'llm_attempt', ['generation_id'], unique=False)
    op.create_index('ix_llm_attempt_pending_enrichment', 'llm_attempt', ['llm_server'], unique=False, postgresql_where=sa.text('enriched_at IS NULL AND generation_id IS NOT NULL'))
    op.create_table('llm_run',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('entry_point', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('git_dirty_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_llm_run'))
    )
    op.create_table('llm_call',
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('llm_server', sa.String(), nullable=False),
    sa.Column('requested_provider', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('call_seconds', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generation_id', sa.String(), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('finish_reason', sa.String(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=True),
    sa.Column('prompt_sha256', sa.String(), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['llm_run.run_id'], name=op.f('fk_llm_call_run_id_llm_run')),
    sa.PrimaryKeyConstraint('call_id', name=op.f('pk_llm_call'))
    )
    op.create_index(op.f('ix_llm_call_run_id'), 'llm_call', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_call_run_id'), table_name='llm_call')
    op.drop_table('llm_call')
    op.drop_table('llm_run')
    op.drop_index('ix_llm_attempt_pending_enrichment', table_name='llm_attempt', postgresql_where=sa.text('enriched_at IS NULL AND generation_id IS NOT NULL'))
    op.drop_index(op.f('ix_llm_attempt_generation_id'), table_name='llm_attempt')
    op.drop_index(op.f('ix_llm_attempt_call_id'), table_name='llm_attempt')
    op.drop_table('llm_attempt')
    # ### end Alembic commands ###